Repository th2-net/th2-gradle-plugin, pull requests merged in 2025-01, with the labels that each got.

#92 [TH2-5270] Remove dependency to docker-plugin
  README.md
  gradle/libs.versions.toml
  plugin/build.gradle.kts
  plugin/src/functionalTest/kotlin/com/exactpro/th2/gradle/Th2BaseGradlePluginFunctionalTest.kt
  plugin/src/functionalTest/kotlin/com/exactpro/th2/gradle/Th2ComponentGradlePluginFunctionalTest.kt
  plugin/src/functionalTest/kotlin/com/exactpro/th2/gradle/Th2GrpcGradlePluginFunctionalTest.kt
  plugin/src/main/kotlin/com/exactpro/th2/gradle/ComponentTh2Plugin.kt
  plugin/src/main/kotlin/com/exactpro/th2/gradle/DockerTh2Extension.kt
  plugin/src/test/kotlin/com/exactpro/th2/gradle/ComponentTh2PluginTest.kt
Labels: enhancement

#97 Prepare next version
  gradle.properties
Labels: ignore

#98 Explicitly specify the JVM version
  .github/workflows/build-and-test.yml
  .github/workflows/publish-gradle-plugin.yml
  .github/workflows/verify-publish-configuration.yml
  plugin/build.gradle.kts
Labels: fix

#100 Prepare next version
  gradle.properties
Labels: ignore
