Repository th2-net/th2-gradle-plugin, pull requests merged in 2025-02, with the labels that each got.

#102 Added verification for application.mainClass into component plugin
  plugin/src/functionalTest/kotlin/com/exactpro/th2/gradle/Th2ComponentGradlePluginFunctionalTest.kt
  plugin/src/functionalTest/kotlin/com/exactpro/th2/gradle/Utils.kt
  plugin/src/main/kotlin/com/exactpro/th2/gradle/ComponentTh2Plugin.kt
  plugin/src/test/kotlin/com/exactpro/th2/gradle/ComponentTh2PluginTest.kt
Labels: enhancement

#105 Prepare next version
  gradle.properties
Labels: ignore

#104 [TH2-5281] Configure Java and Kotlin compilation to use a specific Jvm release target
  .github/workflows/build-and-test.yml
  .github/workflows/publish-gradle-plugin.yml
  .github/workflows/verify-publish-configuration.yml
  gradle.properties
  plugin/build.gradle.kts
  plugin/src/functionalTest/kotlin/com/exactpro/th2/gradle/Th2BaseGradlePluginFunctionalTest.kt
  plugin/src/main/kotlin/com/exactpro/th2/gradle/BaseTh2Plugin.kt
  plugin/src/main/kotlin/com/exactpro/th2/gradle/JavaReleaseTh2Extension.kt
Labels: enhancement

#107 Prepare next version
  gradle.properties
Labels: ignore

#108 Fixed base plugin configuration when targetJavaVersion is 1.8
  plugin/src/functionalTest/kotlin/com/exactpro/th2/gradle/Th2BaseGradlePluginFunctionalTest.kt
  plugin/src/main/kotlin/com/exactpro/th2/gradle/BaseTh2Plugin.kt
Labels: fix

#109 Prepare next version
  gradle.properties
Labels: ignore

#111 Added OWASP credential properties for NVD and KEV
  plugin/src/main/kotlin/com/exactpro/th2/gradle/BaseTh2Plugin.kt
  plugin/src/test/kotlin/com/exactpro/th2/gradle/BaseTh2PluginTest.kt
Labels: enhancement

#115 Prepare next version
  gradle.properties
Labels: ignore
